---
repos:
  - repo: local
    hooks:
      - id: golangci-lint
        name: golangci-lint
        entry: golangci-lint run -c .golangci.yaml --fix
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: check kubeconform
        name: Kubeconform validation
        entry: bash -c <<<-'
          helm template vcluster-argocd-exporter deploy/charts/vcluster-argocd-exporter | kubeconform -strict -output json -summary
          '
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: sast
        name: run security analysis
        entry: gosec ./...
        language: system
        pass_filenames: false
