---
# What vClusters to export
## This is a list of names of vClusters to export (vcluster list)
## defaults to [.Release.Name]
clusters: ~
# If set to true, the exporter will auto-discover all vClusters in the cluster.
# When using this flag, the `clusters` field is ignored.
autoDiscovery: false
# The namespace where ArgoCD has been installed
targetNamespace: argocd
# Debug mode
debug: false

# Internals
commonAnnotations: ~
commonLabels: ~

image:
  repository: ghcr.io/pcanilho/vcluster-argocd-exporter
  tag: 0.1.6@sha256:66b13d15ea00de3d86541d6356d83d5efcf384e141dca1d3d582d028d4778837
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
