---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "app.fullname" . }}-role
  labels:
    {{- include "app.commonLabels" . | indent 4 }}
  annotations:
    {{- include "app.commonAnnotations" . }}
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources: ["*"]
    verbs: ["*"]
