---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "app.fullname" . }}-rolebinding
  labels:
    {{- include "app.commonLabels" . | indent 4 }}
  annotations:
    {{- include "app.commonAnnotations" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "app.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "app.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
