---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | indent 4 }}
  annotations:
    {{- include "app.commonAnnotations" . }}
spec:
  template:
    metadata:
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
      annotations:
        {{- include "app.commonAnnotations" . | indent 4 }}
    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "app.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            {{ .Values.debug | ternary "- --debug" "" }}
            {{ .Values.autoDiscovery | ternary "- --auto-discovery" "" }}
            {{- with .Values.targetNamespace }}
            - -t{{ . }}
            {{- end }}
            {{- with (.Values.clusters | default (list .Release.Name)) }}
              {{- range $_, $cluster := . }}
                {{- if (contains "=" $cluster) }}
                  {{- $parts := split "=" $cluster }}
            - --named-cluster
            - {{$parts._0}}={{$parts._1}}
                {{- else }}
            - -c
            - {{$cluster}}
                {{- end }}
              {{- end }}
            {{- end }}
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: token-volume
              mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              readOnly: true
      volumes:
        - name: token-volume
          projected:
            sources:
              - serviceAccountToken:
                  path: token
                  expirationSeconds: 3600
              - configMap:
                  name: kube-root-ca.crt
                  items:
                    - key: ca.crt
                      path: ca.crt
  backoffLimit: 4
