---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "app.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
      {{- include "app.commonLabels" . | indent 4 }}
  annotations:
    {{- include "app.commonAnnotations" . }}
