name: Release

on:
  push:
    tags: ["v*.*.*"]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          check-latest: true

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Helm Chart
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          helm package deploy/charts/vcluster-argocd-exporter --destination _build --version "$VERSION" --app-version "$VERSION"
          helm push _build/vcluster-argocd-exporter-*.tgz oci://ghcr.io/pcanilho/charts
