name: Test

permissions:
  contents: read
  checks: write

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  pull_request:
    paths-ignore:
      - README.md
      - docs/**
      - .goreleaser.yaml
      - .pre-commit-config.yaml
      - LICENSE
      - .ko.yaml
      - .gitignore
    branches:
      - main
      - release-*

env:
  GO_VERSION: 'stable'
  GOLANGCI_VERSION: 'v1.60'

jobs:
  lint:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: ${{ env.GOLANGCI_VERSION }}

  deploy-test:
    needs: lint
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1

      - name: Prepare k8s Cluster
        run: |
          kubectl create namespace argocd
          kubectl get secret -n argocd vcluster-test || echo "Pass..."
          helm repo add loft-sh https://charts.loft.sh && helm repo update
          helm install test-cluster loft-sh/vcluster \
            --set controlPlane.distro.k0s.enabled=true \
            --version 0.21.0-beta.1 \
            --namespace vcluster \
            --create-namespace \
            --wait
          kubectl get sts -n vcluster
          helm install test-cluster ./deploy/charts/vcluster-argocd-exporter \
            --namespace exporter \
            --timeout 1m \
            --create-namespace \
            --wait \
            --wait-for-jobs || echo "Ignored..."
          kubectl get secret -n argocd test-cluster || echo "Ignored..."
