name: Test

permissions:
  contents: read

on:
  pull_request:
    paths-ignore:
      - README.md
      - docs/**
      - .goreleaser.yaml
      - .pre-commit-config.yaml
      - LICENSE
      - .ko.yaml
      - .gitignore
    branches:
      - main
      - release-*
  push:
    branches-ignore:
      - main
      - release-*
    paths-ignore:
      - README.md
      - docs/**
      - .goreleaser.yaml
      - .pre-commit-config.yaml
      - LICENSE
      - .ko.yaml
      - .gitignore

env:
  GO_VERSION: '1.22.5'
  GOLANGCI_VERSION: 'v1.59.1'

jobs:
  lint:
    timeout-minutes: 5
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: ${{ env.GOLANGCI_VERSION }}

  deploy-test:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1

      - name: Prepare k8s Cluster
        run: |
          kubectl create namespace argocd
          kubectl get secret -n argocd vcluster-test || echo "Pass..."
          helm repo add loft-sh https://charts.loft.sh && helm repo update
          helm install vcluster loft-sh/vcluster \
            --set controlPlane.distro.k0s.enabled=true \
            --version 0.21.0-beta.1 \
            --namespace vcluster \
            --create-namespace \
            --wait
          helm install vcluster deploy/charts/vcluster-argocd-exporter \
            --set clusters={vcluster=vcluster-test} \
            --namespace vcluster \
            --wait
          kubectl get secret -n argocd vcluster-test || echo "Fail..." && exit 1
